[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "anthropic",
    "apscheduler>=3.11.1",
    "faiss-cpu",
    "fastapi",
    "firebase-admin",
    "langchain",
    "langchain-community",
    "langchain-huggingface>=1.1.0",
    "numpy",
    "pydantic-settings",
    "pypdf",
    "pypdf2",
    "python-dotenv",
    "python-multipart",
    "python-pptx",
    "pytz>=2025.2",
    "reportlab",
    "sentence-transformers",
    "torch",
    "transformers",
    "uvicorn[standard]",
]
